### ISSUE TITLE
Pick convention for chemical potential

### ISSUE THREAD

**Issue by jl-wynen** [evanberkowitz/isle#27]
There is some room for defining the chemical potential. It might be better to change it. See #17

**Comment by evanberkowitz** [comment]
@luutom weighing in here would be really helpful.  Does the cns code have µ in it?

**Comment by evanberkowitz** [comment]
Questions to be resolved

 - what is the sign of the chemical potential we want in the Hamiltonian?  `-[a†ha-b†hb]+ρVρ±µQ`?
 - In the diagonal discretization, rather than (1+µ) should we use the fugacity exp(µ).
 - In the diagonal discretization, should we put the chemical potential term on the time diagonal?  Or should we leave it on the time off-diagonal?

**Comment by luutom** [comment]
Hi guys, I'm only just getting accustomed to checking my github account.  As for the convention of the chemical potential, I advocate using a minus sign, as this seems to be the convention for the Hubbard model and condensed matter physics in general.  As for using the fugacity exp(µ) and putting it on the off-diagonal time slice, I have nothing against this.  It seems that keeping things in the exponential and on the off-diagonal time slice seems to have a less discretization errors (i.e. exponential discretization), so maybe it's a good thing to continue this trend.  But in all honesty, I really don't have any feeling one way or another.  BTW, did Ulybeschev et al. use the fugacity term?  I don't think so, right?

**Comment by luutom** [comment]
Early forms of CNS could put in a chemical potential.  But the current version does not, though it's relatively easy to put this in.  I recall using a minus sign convention for the chemical potential, but also not really caring too much about it since the worst I could ever be off compared to some other calculation would be due to a µ --> -µ flip.

**Comment by evanberkowitz** [comment]
When you specify signs, can you say where?  Do you mean put a minus sign in the hamiltonian?  Specifying the sign in the hamiltonian specifies it in the fermion matrix.

**Comment by evanberkowitz** [comment]
> Early forms of CNS could put in a chemical potential. But the current version does not, though it's relatively easy to put this in. I recall using a minus sign convention for the chemical potential, but also not really caring too much about it since the worst I could ever be off compared to some other calculation would be due to a µ --> -µ flip.

At half filling on a bipartite lattice there's a guaranteed `+µ--> –µ` symmetry.  But on non-bipartite lattices that need not be so, so fixing the sign matters.

**Comment by evanberkowitz** [comment]
In [Ulybyshev's thimble paper](https://arxiv.org/pdf/1906.07678.pdf) they pick the Hamiltonian to be `–[a†ha+b†hb]+ρVρ __+__ µQ` (page 6, both hopping terms have the same sign due to bipartiteness).

They also leave the chemical potential as `exp(µ-tilde)` (see the fermion operator in (10)).

**Comment by luutom** [comment]
> When you specify signs, can you say where? Do you mean put a minus sign in the hamiltonian? Specifying the sign in the hamiltonian specifies it in the fermion matrix.

In this case I mean `\begin{aligned}
H & \equiv H_{t b}+H_{U}-\mu \sum_{x}\left(n_{x \uparrow}+n_{x, \downarrow}\right) \\
& \equiv-\kappa \sum_{\langle x, y\rangle, s} a_{x, s}^{\dagger} a_{y, s}+U \sum_{x} n_{x, \uparrow} n_{x, \downarrow}-\mu \sum_{x}\left(n_{x, \uparrow}+n_{x, \downarrow}\right)
\end{aligned}`

**Comment by luutom** [comment]
So maybe we adopt Ulybyshev's convention?

**Comment by evanberkowitz** [comment]
I tend to think `–µQ` tends to make the most sense, because then "large chemical potential" means "incentivize".

**Comment by luutom** [comment]
Great.  I feel no remorse for going against Ulybyshev's convention.

**Comment by evanberkowitz** [comment]
Trying to read the literature, for example [this Scalettar paper](https://www.cond-mat.de/events/correl16/manuscripts/scalettar.pdf) (equation 11) has `–µ ∑ (n_up + n_down) = –µ ∑ (n_a – n_b + 1)`.  Throwing away the constant, their convention also has `–µQ`.

**Comment by jl-wynen** [comment]
Any new insights?

The `–µQ` convention should be what is currently implemented because we used that throughout our notes. (This does however assign a positive charge to particles because of how `Q` is defined.) But Isle uses (ignoring tildes)
`exp(h-µ)` in the exponential and
`(1+µ) - h` in the diagonal discretisation.
Is this consistent? I can't seem to find out where the relative minus sign comes from.

**Comment by evanberkowitz** [comment]
No new insight, but agree with my past-self that `H-µQ` is the right convention (also, need to remember that we have always, in `isle` adopted the positive-particle convention, see #17).

What I'm going to say assumes *no signed hole transformation* (ie. keep the geometry general, possibly non-bipartite, so that `H = -κ Σ_xy [ a† h a – b† h a ] + 1/2 Σ_xy q V q` (and the usual interaction is `V = U δ`, `q= na – nb`) ).  Add to this `–µ Q` with `Q = Σ_x q`.

We can write `H–µQ = – Σ_xy [ a† ( κh + µδ ) a – b† ( κh + µδ ) b ] + 1/2 Σ qVq`.  Then we see that one valid prescription is to just always substitute `κh --> κh + μδ` in the fermion matrix.  This gives one valid prescription, which is what TubesAndBalls.pdf arrives at (22), though there's a sign there that I haven't followed very carefully, but which I reproduce here

    M = (1+µ) δ_x'x δ_t't – κ δ_<x'x> δ_t't – exp( i φ_xt ) δ_x'x δ_t'+1,t

Consider, however, how we go from the exponential discretization (see the ergodicity paper) to the diagonal discretization:  expand in the smallness of the hopping, move the hopping to the time diagonal.  We can make the substitution there and then only expand/move the hopping term, so that an equally valid diagonal finite-µ fermion matrix will look like (again, warning about possibly/probably-inaccurate signs)

    M = δ_x'x δ_t't – κ δ_<x'x> δ_t't – exp( µ + i φ_xt ) δ_x'x δ_t'+1,t

That is, we can keep the exactness of the `fugacity`, which is probably a valuable thing.  Another way to arrive at this is to remember that φ is like a gauge field, and μ can always be gauged away into the temporal gauge field.  If you follow TubesAndBalls I think you can arrive at the same result by using the equation between (17) and (18), `1±iφ = exp(±iφ)` when you actually track the grassman numbers through the derivation.  

Of course in the continuum limit the two had better be equivalent.  But if it were up to me we would
 1. work out the right signs for BOTH approaches (I think TubesAndBalls has a wrong sign but I can't swear to it).
 2. stick to the latter method I describe here, so that rather than doing the "hopping replacement" we do the "phi shift".

**Comment by luutom** [comment]
Evan, I'm currently going over this issue.  Let me take it step by step and use TubesAndBalls.pdf as a starting point.  Do you agree that eq.(1) of TubesAndBalls is using the correct convention, where we assume that `Q=\sum_x (n_{up,x}+n_{down,x})` ?

**Comment by luutom** [comment]
Also, if we switch to your latter method (which I agree would maintain exact fugacity) I worry that this would require a major rewrite of Isle's internals, particularly with regard to the flow routines and force terms?  But this I'm not sure of.  But maybe maintaining exact fugacity is worth it?

**Comment by evanberkowitz** [comment]
> we assume that `Q=\sum_x (n_{up,x}+n_{down,x})`

I think that's right.  `n_up` will become `n_particles` and `n_down` will become `1-n_holes`.  Then the constant term is just a constant which we drop.  That matches what we ultimately settled on in #17, namely: the positive-particle convention.

Whether it requires a "major" rewrite or not is in the eye of the beholder.  I bet @jl-wynen could do it relatively quickly.  However, it might make sense to make an *additional* action (rather than to change a currently-existing one).  We have `exponential` and `diagonal`.  `exponential` already has exact fugacity, `diagonal` does not.  We could add `diagonalFugacity` (or something).

**Comment by luutom** [comment]
But to be clear (on my behalf), the issue of maintaining exact fugacity only applies to the diagonal discretization, correct?  If we decided to only do exponential discretization from now on (I'm actually not advocating this), then this issue of exact fugactiy is moot (assuming we have agreed on a sign convention for Q).

**Comment by evanberkowitz** [comment]
Yes, that's right.  The ambiguity comes when you go to expand the fermion matrix---do you treat the chemical potential like the diagonal part of the hopping matrix, or do you treat it as a shift in phi?

**Comment by luutom** [comment]
Ok, so let's come back to the issue of our sign convention for µ.  If in eq.(1) (of TubesAndBalls) we have µ=0, this does NOT correspond to half-filling in this case.  The half-filling case corresponds to µ=U/2.  So what's usually done is to shift the chemical potential to a point about U/2, i.e. µ --> µ+U/2.  So this is what's done in eq.(2).  So when one sets µ=0 in eq.(2), then this DOES correspond to half-filling.  But for nonzero µ, we still have the same form for the chemical potential as in eq.(1), that is -µQ (see eq.(3)).  This form persists till to eq.(9) (and also the next equation for the balls).  So up to this point we agree that we have the correct sign convention, right?

I'm not presenting any new insights here, I just want to talk my way through this so as to make sure we all agree up to this point.  I realize the issue is with the sign in eq.(22), and that comes next. . .

**Comment by jl-wynen** [comment]
Closing this to clear my backlog
